export enum FeatureType {
    USER = 'user',
    EVENT = 'event',
    ENTERPRISE = 'enterprise',
    VENDOR = 'vendor',
    VENUE= 'venue',
    FORM = 'form',
    PAYMENT = 'payment',
    VENDOR_BOOKING = 'vendor_booking',
    DASHBOARD = 'dashboard',
    VENDOR_MANAGEMENT = 'vendor_management',
    VENUE_MANAGEMENT = 'venue_management',
    SERVICE_CATEGORY = 'service_category',
    MEAL_TYPE = 'meal_type',
    CUISINE = 'cuisine',
    SERVING_STYLE = 'serving_style',
    ADDITIONAL_SERVICE = 'additional_service',
    VENDOR_CATEGORY = 'vendor_category',
    VENUE_BOOKING = 'venue_booking',
    FORM_BUILDER = "form_builder",
    ENTERPRISE_MANAGEMENT = "enterprise_management",
    EVENT_MANAGEMENT = "event_management",
    USER_MANAGEMENT = "user_management",
    EMPLOYEE_MANAGEMENT = "employee_management",
    FEATURE_MANAGEMENT = "feature_management",      
}